// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvt13vozxxX5l_y_DVruQ1gluYBk-Tm2U',
    appId: '1:891748690569:web:6f3d652967d1cf8b723458',
    messagingSenderId: '891748690569',
    projectId: 'upsc-prep-b2336',
    authDomain: 'upsc-prep-b2336.firebaseapp.com',
    storageBucket: 'upsc-prep-b2336.firebasestorage.app',
    databaseURL: 'https://upsc-prep-b2336-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO8JEjGNJv6dmr9fCkLeboo6xa_pcGFs4',
    appId: '1:891748690569:android:4c2310e867988dd2723458',
    messagingSenderId: '891748690569',
    projectId: 'upsc-prep-b2336',
    storageBucket: 'upsc-prep-b2336.firebasestorage.app',
    databaseURL: 'https://upsc-prep-b2336-default-rtdb.firebaseio.com',
  );
}
